sonar.projectKey=10p-SHINE-Notes-App
sonar.projectName=10p SHINE Notes App

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/test,frontend/src

sonar.exclusions=backend/src/test/**,frontend/src/**/__tests__/**
sonar.test.inclusions=backend/src/test/**,frontend/src/**/__tests__/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info